### ISSUE TITLE
null oauth conf when serving login page for path when unprotected page is reached

### ISSUE THREAD

**Issue by maxux** [itsyouonline/caddy-integration#25]
If you use commit 532bc3f8617f3808743abb02c3a489dfd7a5c8fd for exemple, you can protect only some pages (eg `/login`) with `authentication_required` directive. All the others pages should be served without any protection.

Now, if you try to reach an unprotected page, you hit a 500 error: `[ERROR 500 /] null oauth conf when serving login page for path '...'`

Do you know why ?

**Comment by arahmanhamdy** [comment]
@maxux could you send me your caddyfile?

**Comment by arahmanhamdy** [comment]
I think this commit should solve your issue:
https://github.com/itsyouonline/caddy-integration/commit/8636b89bcb026adc8c6532ce02135e803aced495
