### ISSUE TITLE
Dependencies are not vendored

### ISSUE THREAD

**Issue by robvanmieghem** [itsyouonline/caddy-integration#5]
When I run caddydev, I get the following output:
```
COMMAND: go build -o /var/folders/75/br_kw5l577zfjlk20fgfqzmr0000gn/T/caddydev994798178
----
---- # github.com/itsyouonline/caddy-integration/oauth
---- /Users/rob/workspace/go/src/github.com/itsyouonline/caddy-integration/oauth/jwt.go:52: invalid type assertion: token.Claims.(jwt.MapClaims) (non-interface type map[string]interface {} on left)
```
Probably has to do with the version of the jwt library installed in my GOPATH

**Comment by iwanbk** [comment]
vendoring won't solve the issue because:
- caddydev use custom build mechanism, it is going to use jwt-go from $GOPATH
- even the previous problem solved, we will build this plugin from caddy source tree.
